### ISSUE TITLE
Incorrect first item

### ISSUE THREAD

**Issue by jeffreypzh** [michaelbromley/ngx-pagination#235] opened 2018-02-24 01:09 UTC
Hi, 

The first item displayed after using the pagination is incorrect. 

=======

**Angular version**:
5.6.0

**ngx-pagination version**:
3.0.3

**Description of issue**:
I am trying to display more than thousand of results in a page without any sorting. I show only 12 items per page. However, the first result display is incorrect. Please advise.

**Comment by TheBearSO** [comment] 2018-02-28 19:11
Hi @jeffreypzh, we need more details of your issue. If not, is impossible to reproduce.
Additionally, the angular 5.6.0 version doesn't exits, the last version is 5.2.6. 
Here you are a [stackblitz](https://stackblitz.com/edit/angular-uw6j5p) updated with last angular available version and ngx-pagination 3.0.3. Try to reproduce your issue there.

**Comment by michaelbromley** [comment] 2018-06-11 08:56
I'm closing this issue because further data was needed but was not provided. If you want to continue the thread, let me know and I'll re-open it.

**Closed by michaelbromley** 2018-06-11 08:56 UTC
