### ISSUE TITLE
Can't move to current page with data change?

### ISSUE THREAD

**Issue by pramodKLS** [michaelbromley/ngx-pagination#236] opened 2018-03-13 08:27 UTC

**Comment by michaelbromley** [comment] 2018-03-13 09:57
Please take another looks at the issue template and fill it out as best you can:

Hi, thanks for contributing!

This project is maintained in my spare time, so in order to help me address your issue as quickly as 
possible, please provide as much of the following information as you can.

-- Michael 

[^ delete this message]

=======

**Angular version**:

**ngx-pagination version**:

**Description of issue**:

**Steps to reproduce**:

**Expected result**:

**Actual result**:

**Demo**: (if possible, edit [this StackBlitz demo](https://stackblitz.com/edit/angular-e1f9hq) and paste the link to your fork)

Any relevant code:
```

```

**Comment by michaelbromley** [comment] 2018-06-11 08:56
I'm closing this issue because further data was needed but was not provided. If you want to continue the thread, let me know and I'll re-open it.

**Closed by michaelbromley** 2018-06-11 08:56 UTC
