### ISSUE TITLE
next and previous functions are not getting called

### ISSUE THREAD

**Issue by Puja221995** [michaelbromley/ngx-pagination#314] opened 2019-07-12 07:37 UTC
**Angular version**: 7

**Description of issue**: I am trying to create a separate component for pagination. So paginate pipe will be in on one component and pagination-template directive will be in different component. So whenever I am trying to call prev and next function of paginationApi is not working.  So could you please with this like what parametres I need to send from main component to pagination component. 

Any relevant code: <pagination-template #pApi="paginationAPi" (pageChange)="currentPage=$event"> in pagination component.
```

```

**Comment by michaelbromley** [comment] 2019-07-12 08:50
Hi,

first a note on creating issues on GitHub, as I see this is your first:

1. You have put the entire content of your issue in the title. The title should be a short summary of the issue. In your case, something like "next and previous functions are not getting called" would be suitable.
2. The issue body comes pre-filled with a template (you can see it above). The idea is that you read the template and follow its instructions. That is, delete the message from me and then fill out the information requested in bold. 

Please edit the title and issue body (using the "..." menu in the top right of the original issue) as I described and then we can continue.

**Comment by Puja221995** [comment] 2019-07-12 09:02
Thanks for the information. I have edited the issue. Please help.

**Comment by michaelbromley** [comment] 2019-07-12 09:05
Hi, 

you need to show me more code. Ideally reproduce the problem by forking [this StackBlitz demo](https://stackblitz.com/edit/angular-e1f9hq). Otherwise I cannot help if I cannot see what you have actually done.

**Comment by Puja221995** [comment] 2019-07-12 09:07
Will it be fine , If I will share screenshot or that two file code in which I am facing issue.

**Comment by michaelbromley** [comment] 2019-07-12 09:16
It would be much better if you just share the code. Please see [this guide](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) which explains how to use markdown to properly format your code in an issue.

The thing is, this issue tracker is intended for *bugs in the library* rather than support requests (which is what this seems to be). However, I usually do help with support requests but only if you make it really easy for me to help - my time is rather limited. 

Making it easy for me means:

1. Really put in the effort to read the docs, making sure you tried your best to understand the library API.
2. If you still cannot figure it out (it is possible the docs are unclear or do not cover your case) then please provide a minimal reproduction in the form of a code snippet here, or (as mentioned earlier) a runnable StackBlitz demo.

Thanks!

**Comment by Puja221995** [comment] 2019-07-12 09:36
Hi,

Please find the below details. Thank you so much for your time and help.

src/app/pagination/pagination.html
**pagination.html:**

<pagination-template #pApi="paginationApi" (pageChange)="currentPage=$event">
<ul role="navigation">
<li class=''nav"><a (click)="pApi.previous()" id="prev">Previous</li>
<li class="nav"><a (click)="pApi.next()" id="next">Next</li>
</ul>
</pagination-template>

src/app/details/data.html
**dataList.html:**

<table>
<tbody  *ngFor="let data of dataList | paginate : {itmesPerPage:5, currentPage:p}">
<tbody>
<div &ngIf="dataList.length>5">
<appPagination></appPagination>
</div>
</table>


Created one shared service through which I am sharing this currentPage and itemsPerPage value. On click of previous and next I am not getting any error but it's not working . It seems angular is unabel to create paginationApi instance for that page. Please let me know like what needs to be sent from dataList.html to pagination.html.

Thanks

**Comment by Puja221995** [comment] 2019-07-12 09:40
Actually I have written <li> but it's showing as list in comment section and details written for dataList.html is not visible .

**Comment by michaelbromley** [comment] 2019-07-12 09:55
> Created one shared service through which I am sharing this currentPage and itemsPerPage value

This part may be the issue. Since you did not include any code for how you implemented it, I cannot say for sure. 

ps. your html code was not displaying correctly because you did not surround it with the back ticks (```) as described in the article I linked earlier. Here is a more in-depth guide to code formatting: https://help.github.com/en/articles/creating-and-highlighting-code-blocks

**Comment by Puja221995** [comment] 2019-07-12 10:04
Hi,

Thanks for letting me know. Please find the below code. Whenever I am printing this {{pApi.pages.length}}. It is not printing anything BTW I am able to share items per page value between two components, like whenever I am changing itemPerPage value the page is getting updated. Only next and prev is not working . I am not getting what else I need in pagination.ts file from details.ts file. 


src/app/pagination/pagination.html
pagination.html:

```<pagination-template #pApi="paginationApi" (pageChange)="currentPage=$event">
<ul role="navigation">
<li class=''nav"><a (click)="pApi.previous()" id="prev">Previous</li>
<li class="nav"><a (click)="pApi.next()" id="next">Next</li>
{{pApi.pages.length}}
</ul>
</pagination-template>```


src/app/details/data.html
dataList.html:

```<table>
<tbody  *ngFor="let data of dataList | paginate : {itmesPerPage:5, currentPage:p}">
<tbody>
<div &ngIf="dataList.length>5">
<appPagination></appPagination>
</div>
</table>```

dataList.ts

```
thsi.service.currentPage=this.p;
```

**Comment by michaelbromley** [comment] 2019-07-12 11:16
ok. At this point I must insist that you reproduce the issue on StackBlitz. There is simply not enough information for me to help here. With a reproduction I'll probably be able to diagnose the problem quite quickly.

**Comment by Puja221995** [comment] 2019-07-12 11:55
Hi,

I have tried to reproduce the issue.  Please find the below URLS:

https://stackblitz.com/edit/angular-e1f9hq
https://stackblitz.com/edit/angular-e1f9hq?embed=1&file=app/pagination/pagination.component.ts

**Comment by michaelbromley** [comment] 2019-07-12 12:00
Hi, those links are just the original demo. You need to fork it first (press "fork" in the top bar) and then make your changes and make sure to save them and then share that new url.

**Comment by Puja221995** [comment] 2019-07-12 12:49
Hi, Please find the below link.

https://stackblitz.com/edit/angular-sfxd3y

Now it's working  but after two clicks .

**Comment by michaelbromley** [comment] 2019-07-12 18:24
I'm confused by your use of `ngDoCheck`. If you want to communicate the the `currentPage` value has changed, there is a simple and usual way to do it: use an `@Output()` with an `EventEmitter`. Unless you have some very special requirements, using a service to communicate this change is an unusual and non-optimal solution.

If you use an Output and in the AppComponent bind to that output, things should work as expected.

I am going to close this issue now and I advise you to seek other channels for support - I just don't have time to spend on this now, as I am convinced that there is no actual issue with this library itself.

Good luck getting it solved!

**Closed by michaelbromley** 2019-07-12 18:24 UTC
