### ISSUE TITLE
How can I stay in current page after refresh website ?

### ISSUE THREAD

**Issue by Omar-Qalei** [michaelbromley/ngx-pagination#279] opened 2018-10-12 18:43 UTC
**HTML5**
```
<div class="list">
      <pagination-controls (pageChange)="p = $event"></pagination-controls>
 </div>
```

**TS**

`p = 1`

**Comment by egemenu** [comment] 2018-10-13 12:44
I think you better to use query-parameters.

Duplicate of #229

**Comment by Omar-Qalei** [comment] 2018-10-13 12:46
Can you give me example please ?
If I use database will effect to other users

**Comment by egemenu** [comment] 2018-10-13 12:49
What does it have to be with database? I can't follow.

**Closed** 2018-12-10 07:34 UTC
