### ISSUE TITLE
You are fucking guy !!!

### ISSUE THREAD

**Issue by lozthiensu** [michaelbromley/ngx-pagination#207] opened 2017-10-18 13:54 UTC
> interface IServerResponse
> asyncMeals: Observable<string[]>;

I can write english but i feel you are fucking guy, so i write vietnamese.
Bạn thật ngu ngốc khi ép buộc chúng tôi sử dụng Observable string và interface. Đôi khi chúng tôi muốn tạo ra một webapp thật nhanh, chúng tôi sử dụng kiểu dữ liệu asyncMeals: any; Nhưng nó đã không hoạt động, điều này thật ngu ngốc :)

**Comment by michaelbromley** [comment] 2017-10-18 14:24
Translation via Google:

> You're stupid to force us to use Observable String and interfaces. Sometimes when we want to create a very fast webapp, we use the asyncMeals: any data type; But it did not work, this is stupid :)

Sorry, I still don't really understand what the issue is here. I also don't understand if "you are fucking guy" is an insult or not. It's all so confusing!

Now I will translate it into your language: 

Xin lỗi, tôi vẫn không thực sự hiểu những gì vấn đề là ở đây. Tôi cũng không hiểu nếu "bạn là fucking guy" là một sự xúc phạm hay không. Tất cả đều gây nhầm lẫn!

**Comment by HristoKolev** [comment] 2017-10-18 16:07
This is the best issue ever.

**Comment by BioPhoton** [comment] 2017-10-18 20:06
@lozthiensu your issue made my day. 
I alos have some small libs open sourced. Sometimes it is a little bit annoying to work for free for other people and earn maybe a git star or a smily.

But your issue showed me that oss can be lot of fun. Could you please post guy issues on my repos too?

@lozthiensu vấn đề của bạn đã làm cho ngày của tôi. Tôi alos có một số nhỏ libs mở nguồn. Đôi khi nó là một chút khó chịu để làm việc miễn phí cho người khác và kiếm được có thể là một ngôi sao git hoặc một smily. Nhưng vấn đề của bạn cho tôi biết rằng os có thể rất vui vẻ. Bạn có thể xin vui lòng gửi vấn đề guy trên repos của tôi quá?

Best Michael

**Comment by hungdha02** [comment] 2017-10-22 14:35
@lozthiensu V~

**Comment by chung-nguyen** [comment] 2017-10-22 15:18
:man_facepalming: 

@lozthiensu : It's outstandingly ignorant of you to disclose your nationality and ethnic when saying something stupid to somebody. It would make the world think all of your unfortunate countrymen are nuts like you. Since you blame a nice guy who created a free module for your own problem, I guess our nation's gene pool should be free from your idiotic DNA. If you could solve it or have suggestions, make a pull request then.

@michaelbromley, @HristoKolev  and @BioPhoton  : when talking about Vietnamese ethnicity, I hope you will remember greater persons who contributed parts of their lives to the world like Phong-shading rather than such failures of evolution.

**Comment by HristoKolev** [comment] 2017-10-22 15:25
@chung-nguyen I don't know what you are talking about. I'm just upset that only @michaelbromley gets to be a fucking guy...

**Comment by chung-nguyen** [comment] 2017-10-22 15:29
@HristoKolev : I guess they should add a middle finger react emoticon

**Comment by hungdha** [comment] 2017-10-22 15:31
Please close this topic.

**Comment by HristoKolev** [comment] 2017-10-22 15:33
@hungdha No... let's have a little bit of fun. It doesn't  hurt anybody. ;)

**Comment by michaelbromley** [comment] 2017-10-22 18:20
Ok, so I guess I should wrap this issue up then:

@chung-nguyen do not fear, this issue has not given me a bad impression about you or your countrymen. My primary exposure to Vietnamese people and culture is through your national cuisine, which is delicious. One weird GitHub issue is not going to spoil my positive impression. Phong shading is cool too.

@lozthiensu Looks like whatever your actual issue was has now been severely derailed. Sorry about that, but you can kinda blame yourself. Hope you figure it out anyway.

Everyone else: I guess we can all agree that I am a fucking guy and that's now official.

**Closed by michaelbromley** 2017-10-22 18:20 UTC

**Comment by icy** [comment] 2017-10-23 02:45
> Bạn thật ngu ngốc khi ép buộc chúng tôi sử dụng Observable string và interface. Đôi khi chúng tôi muốn tạo ra một webapp thật nhanh, chúng tôi sử dụng kiểu dữ liệu asyncMeals: any; Nhưng nó đã không hoạt động, điều này thật ngu ngốc :)

I'm pretty sure this is not good Vietnamese writing in both formal or informal communication. It's some kind of translation from an English.

Well, I'm going to push new quote to my fun project https://github.com/icy/fortune-vn .

Sorry for this noise.

**Comment by icy** [comment] 2017-10-23 02:54
@hieuhtr thx you (et all) for the thumb down(s). But you are a a true vietnamese, I think you will never write such thing like @lozthiensu wrote because it's very english vietnamese 💯

**Comment by nqtien310** [comment] 2017-10-24 07:06
@lozthiensu The coolest part is you spent like 30 mins trying to write a proper English sentence, then decided to Google translate it into Vietnamese. Great problem-solving skill bro !

Viết tiếng Anh làm gì rồi Google Translate sang tiếng Việt vậy ông nội ?

**Comment by thovo** [comment] 2017-10-24 08:32
As a Vietnamese, I also confused with this issue written in VNese. The saddest part of my life is when I found an issue and reported it to the owner, 2/3 no reply, 1/3 no working solution. By my calculation, its reason is quite clear, I always put in a very clear description and thankful message. Next time 10/10 will try to this approach, it got 10 times of attention from github community 👍

**Comment by michaelbromley** [comment] 2017-10-24 10:17
Out of interest, why is this issue getting so much attention? Has it been posted on some Vietnamese developer forum?

**Comment by HristoKolev** [comment] 2017-10-24 10:19
@michaelbromley I think that they are bashing him for misrepresenting their culture... ? Is this the right place for this?

**Comment by BioPhoton** [comment] 2017-10-24 10:27
The first to apologize is always the bravest. 
The first to forgive is the strongest. 
The first to forget is the happiest.

try to be happy in live. 😉

**Comment by thovo** [comment] 2017-10-24 10:28
@michaelbromley : I just discovered it through a VNese dev channel and I found it interesting. 

@HristoKolev :The culture is something different, it is a lack of creativity and the thirst for knowledge, there is a lot of people prefer to use some predefined library, module and if it can't adapt their needs, they will blame the owner instead of paying their time to read, or make their own module. I still got blamed some time for not using a whole jQuery for selecting an element.

**Comment by icy** [comment] 2017-10-24 10:33
@michaelbromley That's good question. I have seen many similar issues happening frequently, and it's the first time it's officially on Github that's why many people are interested... (maybe?) I think the guy has a good lesson now :) however that's not my point when I posted the first comment here: I just wanted to share the Vietnamese he used is not very vietnamese, so he couldn't mean what he wanted to mean ...
