### ISSUE TITLE
Question about items-per-page

### ISSUE THREAD

**Issue by yeropharaoh** [michaelbromley/ngx-pagination#271] opened 2018-08-15 13:37 UTC
Hi Michael!

Still loving the plugin! 
Right now our issue is that when changing pages it seems like the items are being loaded in/out of the dom; this seems to be causing some delay/jumping of the content when changing pages  (its a list of ul li's with one 5 li's, one li being an svg image). 

However, once we have gone through all the pagination pages, changing pages runs smooth as butter. 

Would you happen to have an idea why this happens and how to fix it? :)

=======

**Angular version**: 6.0.3

**ngx-pagination version**: 3.1.1

Any relevant code:
**in the app.html:**
```
<!--previous -->
<a class="circle circle-left"  (click)="leftArrowJump() ;!p.isFirstPage() ? p.previous() : p.setCurrent(p.getLastPage())"><i class="material-icons arrow">keyboard_arrow_left</i></a>


<!--airline cards -->
<div class="airline-content grid-x grid-margin-x large-up-5 medium-up-3 small-up-1 align-center" id="stuck-prev">
                        <app-airline-card 
                         *ngFor="let airline of shownAirlines | paginate: { itemsPerPage: 20, currentPage: page }" 
                         [airline]="airline">
                         </app-airline-card>
</div>

<!--next -->
 <a class="circle circle-right" (click)="rightArrowJump() ;!p.isLastPage() ? p.next() : p.setCurrent(1)"><i class="material-icons arrow">keyboard_arrow_right</i></a>

<!--pages (dots)-->
    <pagination-template #p="paginationApi" (pageChange)="page = $event">
        <div class="dots-container">
            <div class="dot-div" *ngFor="let page of p.pages">
                <ol id="page-dots"  (click)="p.setCurrent(page.value)">
                    <li [ngClass]="{'active': p.getCurrent() === page.value}">•</li>
                </ol>
            </div>
        </div>
    </pagination-template>
```

**Comment by michaelbromley** [comment] 2018-08-16 07:28
Hi,

* Are you loading the next page async?
* Are you using any Angular animations on the list?

If not the above, perhaps this could be fixed by providing a [trackBy](https://angular.io/api/core/TrackByFunction) to the ngFor. 

Kinda hard for me to know that the issue is exactly without seeing a reproduction of it though.

**Comment by yeropharaoh** [comment] 2018-08-16 08:27
Hi! thanks for getting back to me!

- no angular animations are being used
- I haven't touched how the pages are loaded, it is simply using the code above and in the app.component.ts I have:

```export class AppComponent implements OnInit {
page: number;
}

  filterAirlines(type) {
    if (type === 'all') {
      this.selectedAirlines = "all";
      this.shownAirlines = this.airlines;
    } else {
      this.selectedAirlines = type;
      this.shownAirlines = [];
      for (let i = 0; i < this.airlines.length; i++) {
        if (this.airlines[i].type === type) {
          this.shownAirlines.push(this.airlines[i]);
        }
      }
    }
    this.page = 1;
  }
```

Any ideas? :)

**Comment by michaelbromley** [comment] 2018-08-16 09:00
This is just the way that ngFor works. As I mentioned above, you can alter this by using a trackBy function:
```HTML
<li *ngFor="let item of collection | paginate: { itemsPerPage: 10, currentPage: p }; trackBy: trackByIndex">{{ item }}</li>
```
```ts
trackByIndex(index: number) {
    return index;
}
```

See [this modified demo](https://stackblitz.com/edit/angular-zzsz7h) - you can compare the DOM elements between pages and you'll see that the objects are now identical.

**Comment by yeropharaoh** [comment] 2018-08-16 09:51
Shout out to you! the TrackBy works nicely :)

**Comment by michaelbromley** [comment] 2018-08-16 10:01
Great! Glad that fixed it for you 👍

**Closed by michaelbromley** 2018-08-16 10:01 UTC

**Comment by capynet** [comment] 2019-08-21 23:40
> This is just the way that ngFor works. As I mentioned above, you can alter this by using a trackBy function:
> 
> ```
> <li *ngFor="let item of collection | paginate: { itemsPerPage: 10, currentPage: p }; trackBy: trackByIndex">{{ item }}</li>
> ```
> 
> ```ts
> trackByIndex(index: number) {
>     return index;
> }
> ```
> 
> See [this modified demo](https://stackblitz.com/edit/angular-zzsz7h) - you can compare the DOM elements between pages and you'll see that the objects are now identical.

I cant understand how trackBy solved my flickering effect between pages but it did it o_O

**Comment by michaelbromley** [comment] 2019-08-22 07:47
@capynet From the docs:

> When items are added, moved, or removed in the iterable, the directive must re-render the appropriate DOM nodes. To minimize churn in the DOM, only nodes that have changed are re-rendered.

> By default, the change detector assumes that the object instance identifies the node in the iterable. When this function is supplied, the directive uses the result of calling this function to identify the item node, rather than the identity of the object itself.

So if your object references are changing, then ngFor will remove the DOM node and re-create it, even if it is the "same" from your point of view. So the trackBy function just lets you say to ngFor "Hey, I know that this is not an identical object, but look, the "id" properties are equal, so let's just assume that the objects are the same, ok?", to which ngFor will reply, "Oh, ok then, you know best!", and it will re-use the existing DOM node for that item in the list.
