### ISSUE TITLE
pagination-controls messing up page scroll. 

### ISSUE THREAD

**Issue by Jscott388** [michaelbromley/ngx-pagination#161] opened 2017-05-25 03:51 UTC
=======

**Angular version**: 4.1.2

**ngx-pagination version**: 3.0.0

**Description of issue**: Causing scroll issues. Using clarity framework.

**Steps to reproduce**: When scroll to bottom of page where the page control is, the page expands more with white space. 

**Expected result**: When you take the page-control out, the page stops at the end of content. 

**Actual result**:
If you noticed the scroll bar is showing there is more content below. All white space. The scroll bar appears to be operating normally, but when you see the page controls, the scroll bar resizes and appears page was expanded somehow.
![screen shot 2017-05-24 at 11 47 02 pm](https://cloud.githubusercontent.com/assets/11654505/26435181/685b7198-40db-11e7-9bd9-2c550ebc26e2.png)

If you remove the page controls, the scroll bar works as expected. Scroll stops at bottom of page. 
![screen shot 2017-05-24 at 11 49 25 pm](https://cloud.githubusercontent.com/assets/11654505/26435216/adffdf86-40db-11e7-8db9-b855cf8cd02f.png)

**Comment by michaelbromley** [comment] 2017-05-25 06:28
Hi,

When you inspect the DOM, what is it that is actually taking up all that white space at the bottom of your first example?

**Comment by michaelbromley** [comment] 2017-06-22 07:57
I'm closing this issue because further data was needed but was not provided. If you want to continue the thread, let me know and I'll re-open it.

**Closed by michaelbromley** 2017-06-22 07:57 UTC

**Comment by Vaishnavi6121995** [comment] 2019-05-22 07:01
Hello @michaelbromley I need to move to the top of the page when page number 2 is clicked can u please help me

**Comment by joshua0095** [comment] 2022-08-09 03:01
I have the same issue. The DOM that is actually taking up all that white space at the bottom is HTML

**Comment by renatohmc** [comment] 2023-10-30 20:47
I have the same issue. Does anyone know how to solve it?

**Comment by michaelbromley** [comment] 2023-11-01 09:44
@renatohmc are you able to put together a reproduction on StackBlitz (starter: https://stackblitz.com/edit/angular-e1f9hq?file=app%2Fapp.component.ts) or as a stand-alone minimal repo on GitHub?
