### ISSUE TITLE
Pagination is not working properly inside nested loop

### ISSUE THREAD

**Issue by vcarrin1** [michaelbromley/ngx-pagination#189] opened 2017-08-23 22:09 UTC
Hi, 

**Angular version**: 2

**ngx-pagination version**: 3.0.1

**Description of issue**: 
Pagination is not working inside nested for loop. In the example below I am looping through data to group by a field and then on the data based on the grouping I want to paginate, which is an array. The result that I get is pagination is set to 1 page and the list of result is equal to itemsPerPage.

Is there a solution to this or the library doesn't support it? Thank you.

Any relevant code:
```
<tabset>
     <tab *ngFor="let object of objectsData.entries | groupBy: 'physical_object_type_name' | keyobject " class="clearfix" heading="{{object.key}}">
           <div  *ngFor="let item of object.value | paginate: { id:'normal', itemsPerPage: 10, currentPage: p1  }">
                <button class="btn btn-primary" type="button" (click)="getDetails(item);lgModalShow();">
                   {{item.database_name}}.{{item.physical_object_name | truncate : 25: '...' }}
               </button>
           </div>
     </tab>
 </tabset>

<pagination-controls id="normal" class="my-pagination" (pageChange)="p1 = $event"></pagination-controls>
```

**Comment by michaelbromley** [comment] 2017-08-24 08:29
Hi,

I don't quite understand this line:
> The result that I get is pagination is set to 1 page and the list of result is equal to itemsPerPage.

But in general, what you are attempting to do *is* possible. One this that I noticed in your code is that you assign the id "normal" to all the pagination instances. This is likely the cause of your problem. 

Also another thing that doesn't make sense to me is that you have only a single pagination-controls, even though you may have several paginated lists. Is this intentional? What is the idea here?

The usual pattern would be to move the `pagination-controls` up inside the outer ngFor loop so that it is coupled together with just *one* pagination instance. Then generate a unique `id` and `currentPage` for every pagination instance created by the outer loop. 

Here is an example from the [docs](https://github.com/michaelbromley/ngx-pagination/tree/20a2db2501b842826e28031f5d0e2c894401a2b9#multiple-instances):

```TypeScript
export class MyComponent {
  p: number[] = [];
}
```
```HTML
<div *ngFor="let id of [1, 2]; let i = index;">
  <ul>
    <li *ngFor="let item of collection | paginate: { itemsPerPage: 10, currentPage: p[i], id: id }">{{ item }}</li>
   </ul>
   <pagination-controls (pageChange)="p[i] = $event" [id]="id"></pagination-controls>
</div>
```

**Comment by vcarrin1** [comment] 2017-08-24 21:19
Thank you for your quick reply.  The issues was indeed in the id, I had to generate a unique id for each instance. I got it to work, but the currentPage highlight is not working when moving through pages. 

<tabset>
                <tab *ngFor="let object of objectsData.entries | groupBy: 'physical_object_type_name' | keyobject; let i = index; " class="clearfix" heading="{{object.key}}">
                  <div id="inline-buttons" *ngIf="objectsData" class="clearfix">
                    <div  *ngFor="let item of object.value | paginate: { id:object.key, itemsPerPage: 10, currentPage: p[i]  }">
                      <button class="btn btn-primary" type="button" (click)="getDetails(item);lgModalShow();">
                        {{item.database_name}}.{{item.physical_object_name | truncate : 25: '...' }}
                      </button>
                    </div>
                  </div>
                  <div>
                    <br/>
                    <pagination-controls [id]="id" class="my-pagination" (pageChange)="p[i] = $event"></pagination-controls>
                  </div>
                </tab>
              </tabset>

**Comment by michaelbromley** [comment] 2017-11-19 19:32
Hi, not sure whether you fixed this yourself already, but the behaviour you reported is sometimes caused by the currentPage value being passed as a string rather than a number. This was fixed in a recent release.

I'll close this now but let me know if there is still an issue with that.

**Closed by michaelbromley** 2017-11-19 19:32 UTC

**Comment by kata419** [comment] 2018-11-22 13:11
not working properly only one page it is showing

**Comment by lakshay2711** [comment] 2019-04-08 10:52
> ```
> id 
> ```



> Hi,
> 
> I don't quite understand this line:
> 
> > The result that I get is pagination is set to 1 page and the list of result is equal to itemsPerPage.
> 
> But in general, what you are attempting to do _is_ possible. One this that I noticed in your code is that you assign the id "normal" to all the pagination instances. This is likely the cause of your problem.
> 
> Also another thing that doesn't make sense to me is that you have only a single pagination-controls, even though you may have several paginated lists. Is this intentional? What is the idea here?
> 
> The usual pattern would be to move the `pagination-controls` up inside the outer ngFor loop so that it is coupled together with just _one_ pagination instance. Then generate a unique `id` and `currentPage` for every pagination instance created by the outer loop.
> 
> Here is an example from the [docs](https://github.com/michaelbromley/ngx-pagination/tree/20a2db2501b842826e28031f5d0e2c894401a2b9#multiple-instances):
> 
> ```ts
> export class MyComponent {
>   p: number[] = [];
> }
> ```
> 
> ```
> <div *ngFor="let id of [1, 2]; let i = index;">
>   <ul>
>     <li *ngFor="let item of collection | paginate: { itemsPerPage: 10, currentPage: p[i], id: id }">{{ item }}</li>
>    </ul>
>    <pagination-controls (pageChange)="p[i] = $event" [id]="id"></pagination-controls>
> </div>
> ```

Hi michaelbromley,

In the first ngFor look (id of [1, 2]) and the following id you are using in the second for loop(id: id), 
Here id you mean id as a number or it is just an object. 

Thanks
Lakshay
