### ISSUE TITLE
Page Change Event fires thrice resulting in wrong event to be fired

### ISSUE THREAD

**Issue by Liahus3003** [michaelbromley/ngx-pagination#259] opened 2018-06-20 06:35 UTC
Angular: 5

ngx-pagination: 3.1.1

Description: pageChange event is called 3 times

Scenario : I have total of 5 items with 4 per page. I click on page 2 expecting 1 item to be loaded , after that 1 item is loaded an another pageChange event is fired (**twice**) with pageNumber as 1 resulting in going back to page 1.

**Comment by michaelbromley** [comment] 2018-06-20 08:30
Hi,

Are you able to produce a reproduction of this issue using the [StackBlitz demo](https://stackblitz.com/edit/angular-e1f9hq) as a starting point? Just fork it and make your changes and paste the link back.

Failing that, at the bare minimum please post some code so I might have a chance to figure out what the problem might be.

**Comment by michaelbromley** [comment] 2018-08-08 14:34
I'm closing this issue because further data was needed but was not provided. If you want to continue the thread, let me know and I'll re-open it.

**Closed by michaelbromley** 2018-08-08 14:34 UTC
