### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by joncorrin** [michaelbromley/ngx-pagination#170] opened 2017-06-21 00:57 UTC
=======

**Angular version**:
4.0

**ngx-pagination version**:
3.0.0

**Description of issue**:
Using pagination-template with bulma CSS framework on Angular 4.0. Getting RangeError: Maximum call stack size exceeded on         <ul class="pagination-list" *ngFor="let page of p.pages">

**Steps to reproduce**:

**Expected result**:

**Actual result**:
RangeError: Maximum call stack size exceeded

**Demo**: (if possible, edit [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) and paste the link to your fork)

Any relevant code:
```
 <div class="box">
    <article class="media" *ngFor="let drive of drives | paginate: { itemsPerPage: 3,
    currentPage: p}">
      <figure class="media-left">
        <p class="image is-64x64">
          <img src="../../../assets/images/default-profile.png" alt="Atlas profile image">
        </p>
      </figure>
      <div class="media-content">
        <content>
          <p>
            <strong>User First and Last Name</strong><br>
            {{drive.startLocation}}<br>
            {{drive.tripDate | date: 'MM/dd/yyyy'}} at {{drive.tripHour}} hr <br>
            Seats available: {{drive.numberOfPassengers}} seats <br>
            Price per seat: ${{drive.price}} <br>
          </p>

        </content>
      </div>
    </article>
    <pagination-template
      #p="paginationApi"
      (pageChange)="pageChange.emit($event)">
      <nav class="pagination is-centered">
        <a class="pagination-previous" (click)="p.previous()">Previous</a>
        <a class="pagination-next" (click)="p.next()">Next</a>
        <ul class="pagination-list" *ngFor="let page of p.pages">
          <li *ngIf="p.getCurrent() !== page.value">
            <a class="pagination-link" (click)="p.setCurrent(page.value)">{{page.label}}</a>
          </li>
          <li *ngIf="p.getCurrent() === page.value">
            <div class="pagination-link is-current">{{page.label}}</div>
          </li>
        </ul>
      </nav>
    </pagination-template>
```

**Comment by michaelbromley** [comment] 2017-06-21 07:53
Hi,

Can you provide a stack trace for the error? 

What is the value of `p.pages` when this error occurs?

Need a little more info to help out here. Never seen this problem before.

**Comment by joncorrin** [comment] 2017-06-21 18:05
The error I get upon starting the app is : 
`RideListComponent.html:25 ERROR RangeError: Maximum call stack size exceeded
    at isViewDebugError (core.es5.js:8525)
    at callWithDebugContext (core.es5.js:13542)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (core.es5.js:13075)
    at ViewRef_.detectChanges (core.es5.js:10256)
    at ngx-pagination.js:312
    at SafeSubscriber.schedulerFn [as _next] (core.es5.js:3647)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:238)
    at SafeSubscriber.next (Subscriber.js:185)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
View_RideListComponent_0	@	RideListComponent.html:25
proxyClass	@	compiler.es5.js:14962
DebugContext_.logError	@	core.es5.js:13475
ErrorHandler.handleError	@	core.es5.js:1080
ApplicationRef_.tick	@	core.es5.js:4872
(anonymous)	@	core.es5.js:4743
webpackJsonp.519.ZoneDelegate.invoke	@	zone.js:391
onInvoke	@	core.es5.js:3933
webpackJsonp.519.ZoneDelegate.invoke	@	zone.js:390
webpackJsonp.519.Zone.run	@	zone.js:141
NgZone.run	@	core.es5.js:3801
next	@	core.es5.js:4743
schedulerFn	@	core.es5.js:3635
SafeSubscriber.__tryOrUnsub	@	Subscriber.js:238
SafeSubscriber.next	@	Subscriber.js:185
Subscriber._next	@	Subscriber.js:125
Subscriber.next	@	Subscriber.js:89
Subject.next	@	Subject.js:55
EventEmitter.emit	@	core.es5.js:3621
NgZone.checkStable	@	core.es5.js:3898
NgZone.onLeave	@	core.es5.js:3974
onInvokeTask	@	core.es5.js:3927
webpackJsonp.519.ZoneDelegate.invokeTask	@	zone.js:423
webpackJsonp.519.Zone.runTask	@	zone.js:191
ZoneTask.invoke`

and this error as well: 
`ERROR CONTEXT 
DebugContext_ {view: Object, nodeIndex: 28, nodeDef: Object, elDef: Object, elView: Object}
View_RideListComponent_0	@	RideListComponent.html:25
proxyClass	@	compiler.es5.js:14962
DebugContext_.logError	@	core.es5.js:13475
ErrorHandler.handleError	@	core.es5.js:1085
ApplicationRef_.tick	@	core.es5.js:4872
(anonymous)	@	core.es5.js:4743
webpackJsonp.519.ZoneDelegate.invoke	@	zone.js:391
onInvoke	@	core.es5.js:3933
webpackJsonp.519.ZoneDelegate.invoke	@	zone.js:390
webpackJsonp.519.Zone.run	@	zone.js:141
NgZone.run	@	core.es5.js:3801
next	@	core.es5.js:4743
schedulerFn	@	core.es5.js:3635
SafeSubscriber.__tryOrUnsub	@	Subscriber.js:238
SafeSubscriber.next	@	Subscriber.js:185
Subscriber._next	@	Subscriber.js:125
Subscriber.next	@	Subscriber.js:89
Subject.next	@	Subject.js:55
EventEmitter.emit	@	core.es5.js:3621
NgZone.checkStable	@	core.es5.js:3898
NgZone.onLeave	@	core.es5.js:3974
onInvokeTask	@	core.es5.js:3927
webpackJsonp.519.ZoneDelegate.invokeTask	@	zone.js:423
webpackJsonp.519.Zone.runTask	@	zone.js:191
ZoneTask.invoke`


Two buttons appear, the previous and next buttons shown in the code above. Upon clicking one of them, a 1 button appears and stays. This error is then received: 

`RideListComponent.html:44 ERROR TypeError: Cannot read property 'emit' of undefined
    at Object.eval [as handleEvent] (RideListComponent.html:46)
    at handleEvent (core.es5.js:12076)
    at callWithDebugContext (core.es5.js:13535)
    at Object.debugHandleEvent [as handleEvent] (core.es5.js:13123)
    at dispatchEvent (core.es5.js:8688)
    at core.es5.js:10850
    at SafeSubscriber.schedulerFn [as _next] (core.es5.js:3647)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:238)
    at SafeSubscriber.next (Subscriber.js:185)
    at Subscriber._next (Subscriber.js:125)
View_RideListComponent_0	@	RideListComponent.html:44
proxyClass	@	compiler.es5.js:14962
DebugContext_.logError	@	core.es5.js:13475
ErrorHandler.handleError	@	core.es5.js:1080
(anonymous)	@	core.es5.js:10854
schedulerFn	@	core.es5.js:3647
SafeSubscriber.__tryOrUnsub	@	Subscriber.js:238
SafeSubscriber.next	@	Subscriber.js:185
Subscriber._next	@	Subscriber.js:125
Subscriber.next	@	Subscriber.js:89
Subject.next	@	Subject.js:55
EventEmitter.emit	@	core.es5.js:3621
PaginationControlsDirective.setCurrent	@	ngx-pagination.js:358
PaginationControlsDirective.next	@	ngx-pagination.js:340
(anonymous)	@	RideListComponent.html:49
handleEvent	@	core.es5.js:12076
callWithDebugContext	@	core.es5.js:13535
debugHandleEvent	@	core.es5.js:13123
dispatchEvent	@	core.es5.js:8688
(anonymous)	@	core.es5.js:9299
(anonymous)	@	platform-browser.es5.js:2668
webpackJsonp.519.ZoneDelegate.invokeTask	@	zone.js:424
onInvokeTask	@	core.es5.js:3924
webpackJsonp.519.ZoneDelegate.invokeTask	@	zone.js:423
webpackJsonp.519.Zone.runTask	@	zone.js:191
ZoneTask.invoke`

as well as this error: 
`ERROR CONTEXT 
DebugContext_ {view: Object, nodeIndex: 32, nodeDef: Object, elDef: Object, elView: Object}
View_RideListComponent_0	@	RideListComponent.html:44
proxyClass	@	compiler.es5.js:14962
DebugContext_.logError	@	core.es5.js:13475
ErrorHandler.handleError	@	core.es5.js:1085
(anonymous)	@	core.es5.js:10854
schedulerFn	@	core.es5.js:3647
SafeSubscriber.__tryOrUnsub	@	Subscriber.js:238
SafeSubscriber.next	@	Subscriber.js:185
Subscriber._next	@	Subscriber.js:125
Subscriber.next	@	Subscriber.js:89
Subject.next	@	Subject.js:55
EventEmitter.emit	@	core.es5.js:3621
PaginationControlsDirective.setCurrent	@	ngx-pagination.js:358
PaginationControlsDirective.next	@	ngx-pagination.js:340
(anonymous)	@	RideListComponent.html:49
handleEvent	@	core.es5.js:12076
callWithDebugContext	@	core.es5.js:13535
debugHandleEvent	@	core.es5.js:13123
dispatchEvent	@	core.es5.js:8688
(anonymous)	@	core.es5.js:9299
(anonymous)	@	platform-browser.es5.js:2668
webpackJsonp.519.ZoneDelegate.invokeTask	@	zone.js:424
onInvokeTask	@	core.es5.js:3924
webpackJsonp.519.ZoneDelegate.invokeTask	@	zone.js:423
webpackJsonp.519.Zone.runTask	@	zone.js:191
ZoneTask.invoke`

I could not trace the value of p.pages, I tried inputting it into the template as {{ p.pages.valueOf() }} but recieved [object Object] as text on the web page.

**Comment by michaelbromley** [comment] 2017-06-21 19:15
Okay, one of the errors *does* make a little sense: `Cannot read property 'emit' of undefined` - I suspect this may be coming from this line: 

```
<pagination-template
      #p="paginationApi"
      (pageChange)="pageChange.emit($event)">
```

Do you have in your component class an EventEmitter named "pageChange"? Sounds like maybe not.

As for the "maximum call stack" error, it says it comes from line 312 of the compiled js file, which looks like it corresponds to [this line](https://github.com/michaelbromley/ngx-pagination/blob/6e29e4e15ef347a187963d91c75b34a22aec744a/src/pagination-controls.directive.ts#L34) in the original source code.

Maybe open up the file "ngx-pagination.js" in your "node_modules" folder and put a `debugger;` statement there before that line, so you can try to figure out what is going wrong. Sounds like there might be an infinite loop for some reason.

(ps, to format multi-line blocks of code, use three backticks "```" before and after rather than one. Makes it more readable.)

**Comment by joncorrin** [comment] 2017-06-21 20:08
After adding the event emitter, the second issue was resolved. 

I am still uncertain about the first error. I placed a debugger; statement and this is what I am receiving. 

`var PaginationControlsDirective = (function () {
    function PaginationControlsDirective(service, changeDetectorRef) {
        var _this = this;
        this.service = service;
        this.changeDetectorRef = changeDetectorRef;
        this.maxSize = 7;
        this.pageChange = new EventEmitter();
        this.pages = [];
        this.changeSub = this.service.change
            .subscribe(function (id) {
            if (_this.id === id) {
              debugger;
                _this.updatePageLinks();
                _this.changeDetectorRef.markForCheck();
                _this.changeDetectorRef.detectChanges();
            }
        });
    }`

**Comment by joncorrin** [comment] 2017-06-21 20:09
```var PaginationControlsDirective = (function () {
    function PaginationControlsDirective(service, changeDetectorRef) {
        var _this = this;
        this.service = service;
        this.changeDetectorRef = changeDetectorRef;
        this.maxSize = 7;
        this.pageChange = new EventEmitter();
        this.pages = [];
        this.changeSub = this.service.change
            .subscribe(function (id) {
            if (_this.id === id) {
              debugger;
                _this.updatePageLinks();
                _this.changeDetectorRef.markForCheck();
                _this.changeDetectorRef.detectChanges();
            }
        });
    } ```

**Comment by joncorrin** [comment] 2017-06-21 20:09
Sorry ! look at the second comment

**Comment by joncorrin** [comment] 2017-06-21 20:19
Sorry again, this is the debugger.
![screen shot 2017-06-21 at 1 18 28 pm](https://user-images.githubusercontent.com/23392999/27404796-3228724c-5684-11e7-95dd-92c896f5307b.png)

**Comment by michaelbromley** [comment] 2017-06-22 07:18
Is that debugger point being hit over and over or just once?

At this stage I think you need to try to put together a reproduction case so that I can help further. I'd really need to dig into it to debug whatever it is. If you are able to reproduce it in a plunker demo (you can use [this](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) as the starting point) then I'll try to help further.

**Comment by joncorrin** [comment] 2017-06-22 23:32
http://plnkr.co/edit/UQYPW9GnR4isIkzLoxRi?p=preview

I believe this plunker is producing the same maxiumum call stack error.

**Comment by michaelbromley** [comment] 2017-06-23 07:35
Thanks for the demo - I was able to find out the problem: It is because you have 2 variables named "p" - one is the current page, and the other is the template variable for the `paginationApi`. If you make the names distinct, then the error goes away.

**Comment by joncorrin** [comment] 2017-06-23 18:33
Thanks! I changed all of the "p" variables in pagination-template to "pT" and it resolved the call max stack error. Now I am getting: 

```
ERROR TypeError: Cannot read property 'emit' of undefined
    at Object.eval [as handleEvent]
```

I was able to get duplicate on this link: http://plnkr.co/edit/wimr2T7tqK1fcr2eASeO?p=preview

I played around with the EventEmitter with no luck.

**Comment by michaelbromley** [comment] 2017-06-25 19:22
The problem is here:

```TypeScript
 @Output() pageChange: EventEmitter<number>;
```

You declare a class variable named "pageChange", and you declare that it is of type `EventEmitter<number>`, but you fail to actually assign it a value anywhere. This is why it is `undefined`, as the error message points out. To make it more clear, consider this code:

```TypeScript
const age: number;
const doubleAge = age * 2; // error here, age is undefined
```

The solution is to actually assign it a value, like this:
```TypeScript
 @Output() pageChange = new EventEmitter<number>();
```
Note that in this case, there is no need to additionally specify the type, since it can be inferred from the value to be of type `EventEmitter<number>`.

**Comment by joncorrin** [comment] 2017-06-26 04:44
Thank you. I hate to keep bothering you like this, but I just cannot seem to get it to work properly. The error has disappeared but I'm getting no response when clicking. I placed a few console.logs in the source code to track if the button was being clicked, and the next button responds but clicking a specific page number does not. The next button also does not push to the next page, it just sends the log to the console.



Heres the code Im using to debug (vendor.bundle.js 73839)

```
   PaginationControlsDirective.prototype.previous = function () {
      console.log('Previous clicked');
        this.checkValidId();
        this.setCurr  ent(this.getCurrent() - 1);
    };
    /**
     * Go to the next page
     */
    PaginationControlsDirective.prototype.next = function () {
      console.log('Next clicked')
        this.checkValidId();
        this.setCurrent(this.getCurrent() + 1);
    };
```

and (ngx-pagination.umd.js at 360)


```
 PaginationControlsDirective.prototype.setCurrent = function (page) {
      console.log('Set current clicked');
        this.pageChange.emit(page);
    };
    /**
```

Heres my component.ts 

```
export class DriveListComponent implements OnInit {
  @Input() id = 'first';
  @Input() maxSize: number;
  @Output() pageChange = new EventEmitter<number>();
  p1 = 1;


  drives: Drive[];
```

and finally my component.html (specifically the ngx-pagination custom directive code). As a note: I added the id number after it already was not responding. 
 ```
<pagination-template
    #pT="paginationApi"
    (pageChange)="pageChange.emit($event)" id="first">
    <nav class="pagination is-centered">
      <div class="pagination-previous">
        <p *ngIf="pT.isFirstPage()"><<</p>
        <a  *ngIf="!pT.isFirstPage()" (click)="pT.previous()"><<</a>
      </div>
      <a class="button is-centered" routerLink="/new-ride">Create Ride Request</a>
      <div class="pagination-next">
        <p *ngIf="pT.isLastPage()">>></p>
        <a  *ngIf="!pT.isLastPage()" (click)="pT.next()">>></a>
      </div>
      <ul class="pagination-list" *ngFor="let page of pT.pages">
        <li *ngIf="pT.getCurrent() !== page.value">
          <a class="pagination-link" (click)="pT.setCurrent(page.value)">{{page.label}}</a>
        </li>
        <li *ngIf="pT.getCurrent() === page.value">
          <div class="pagination-link is-current">{{page.label}}</div>
        </li>
      </ul>
    </nav>
  </pagination-template>
```

**Comment by joncorrin** [comment] 2017-06-26 05:02
Here is a plunker http://plnkr.co/edit/wimr2T7tqK1fcr2eASeO?p=preview

**Comment by joncorrin** [comment] 2017-06-26 05:37
I'm now getting this error

```
ERROR TypeError: Cannot read property 'isLastPage' of undefined
    at Object.eval [as updateRenderer] (ng:///AppModule/DriveListComponent.ngfactory.js:194)
    at Object.debugUpdateRenderer [as updateRenderer] (vendor.bundle.js:13913)
    at checkAndUpdateView (vendor.bundle.js:13062)
    at callViewAction (vendor.bundle.js:13420)
    at execComponentViewsAction (vendor.bundle.js:13352)
    at checkAndUpdateView (vendor.bundle.js:13063)
    at callViewAction (vendor.bundle.js:13420)
    at execComponentViewsAction (vendor.bundle.js:13352)
    at checkAndUpdateView (vendor.bundle.js:13063)
    at callViewAction (vendor.bundle.js:13420)
```

I think I'm having an issue with .isLastPage() and .getCurrent()

**Comment by michaelbromley** [comment] 2017-06-26 07:56
Hi,

I looked at your plunker. You had just failed to rename some instances of `p` to `pT`:

```HTML
<div class="pagination-next" [class.disabled]="p.isLastPage()">
      <a *ngIf="!pT.isLastPage()" (click)="pT.next()"> > </a>
    </div>
```

General debugging tip: When you get an error like "Cannot read property 'something' of undefined", it means your code is trying to access or use the property "something" of an object which either does not exist or has had no value assigned to it. Simply search for all instances of "something" in your code and you will soon find the issue.

> The error has disappeared but I'm getting no response when clicking. 

This is because you have this code:

```HTML
<pagination-template #pT="paginationApi"
                       (pageChange)="pageChange.emit($event)" id="first">
```

So you are telling it to emit a `pageChange` event on the EventEmitter you defined in your class, but that's it. The event gets emitted, but there is nothing there to respond to the event. Hence the page does not update.

It looks like you might not even need the EventEmitter - this would only be required if you intend to pass the event up to a parent component and handle it there. If you just want to handle the page change internally in this component, you can directly assign to the currentPage `p` value:

```HTML
<pagination-template #pT="paginationApi"
                       (pageChange)="p = $event" id="first">
```

I want to know - and I in no way mean to come across as condescending here - what your experience with JS and Angular are? I have no problem helping, but it is useful for me to know that so that I know how to address my responses.

**Comment by joncorrin** [comment] 2017-06-26 14:31
Thanks, Michael. 

I've been working with JS softly for about under a year and Angular for a little over 6 months. You resolved my issue with the removal of the event emitter. The pagination now works, with Bulma. 

My honest thought process was the EventEmitter was hooking up to the source code, but I understand now that is not the case, and that it's reaching out to the pagination Pipe. 

I appreciate you working with me and explaining resolutions simply.

**Comment by michaelbromley** [comment] 2017-06-26 18:57
Ok, glad you got it sorted. Angular has a large API and is a lot to take in, especially if relatively new to JavaScript. If you've not done been through the [fundamentals in the docs](https://angular.io/guide/architecture), it's worth spending a little time to read through. It'll clear up things like the role of EventEmitters and so on.

Good luck!

**Closed by michaelbromley** 2017-06-26 18:57 UTC
