### ISSUE TITLE
https://github.com/michaelbromley/ngx-pagination/issues/127

### ISSUE THREAD

**Issue by kanishkamehta20** [michaelbromley/ngx-pagination#275] opened 2018-09-20 08:46 UTC
**Angular version**: 5.2.0

**ngx-pagination version**: 3.2.0

**Description of issue**: Listing in pagination works correctly but page active is incorrect.

**Steps to reproduce**: Implement pagination in application, click on page 2, from page 2 , click on any item, navigate to other component, comes back with query params as page 2, listing reflect on paginated component is correct but page active is 1.

**Expected result**: Implement pagination in application, click on page 2, from page 2 , click on any item, navigate to other component, comes back with query params as page 2, listing reflect on paginated component is correct, active page should be 2.

**Actual result**: Implement pagination in application, click on page 2, from page 2 , click on any item, navigate to other component, comes back with query params as page 2, listing reflect on paginated component is correct but page active is 1.

I will add a demo if necessary. Please let me know if there is an issue or if I need to find a different way to handle my linking capabilities.
Thanks in advance!

**Comment by michaelbromley** [comment] 2018-09-20 12:11
Hi,

> Implement pagination in application, click on page 2, from page 2 , click on any item, navigate to other component, comes back with query params as page 2, listing reflect on paginated component is correct but page active is 1.

It is unclear to me from this description what is going on exactly. A demo and / or some code snippets would help here.

Also, please could you edit the title of the issue to give it a more descriptive name. Currently it is just the URL of another issue and I don't understand why.

**Comment by michaelbromley** [comment] 2018-11-30 12:40
@irrfan13 Please use the provided [StackBlitz demo](https://stackblitz.com/edit/angular-e1f9hq) to put together a reproduction of the issue, otherwise I can't help.

**Comment by irrfan13** [comment] 2018-12-03 04:36
@michaelbromley  I am sorry i can not show this in demo if i do it I have to import the service. I have given the component function.
 `| paginate: { itemsPerPage: 15, id: 'serverPaging', currentPage: p, totalItems: totalRecords`
`<pagination-controls (pageChange)="getPage($event)" id="serverPaging" autoHide="true"	class="paginateResults"></pagination-controls>	`
In my question `(pageChange) = getPage($event)` is sending the event and storing the event value to P, when in template for `currentPage: p` the value is page number is not changing from 1 to 2 when i click on page number 2 in pagination control.

**Comment by kanishkamehta20** [comment] 2018-12-03 05:01
> Hi for server side paging
> onload initially i have set page number 1, but while clicking on page number 2 the page focus is not changing its still on page number 1 but, the records of page number 2 displayed on UI.
> 
> in template
> `pageChange=getPage($event)`
> 
> in component
> `page:number; and = 1 (tried both)`
> 
> ```
> getPage(page){
> 		 this.service.getData(data).subscribe((response)=>{
>                         this.p = page;
>                         this.resultData = response;
>                         this.totalRecords = response.totalRecs;
> })
> ```

@irrfan13 Once you fetch all the records from service, then only change the page number and then it will work correctly, I am also facing the same problem.

For Ex : 

getPage(page){
		 this.service.getData(data).subscribe((response)=>{
                        
                        this.resultData = response;
                        this.totalRecords = response.totalRecs;
                        this.p = page;
})

**Comment by irrfan13** [comment] 2018-12-05 04:11
Hi 
I resolved the issue, it was my mistake i was using same variable for currentPage in template, so it was setting it to 1 every time

**Comment by michaelbromley** [comment] 2018-12-05 07:44
Ok looks like you both got your issues sorted, so I'll close this now 👍

**Closed by michaelbromley** 2018-12-05 07:44 UTC

**Comment by irrfan13** [comment] 2018-12-06 04:02
> Ok looks like you both got your issues sorted, so I'll close this now 👍

thank you @michaelbromley

**Comment by irrfan13** [comment] 2018-12-06 04:04
> > Hi for server side paging
> > onload initially i have set page number 1, but while clicking on page number 2 the page focus is not changing its still on page number 1 but, the records of page number 2 displayed on UI.
> > in template
> > `pageChange=getPage($event)`
> > in component
> > `page:number; and = 1 (tried both)`
> > ```
> > getPage(page){
> > 		 this.service.getData(data).subscribe((response)=>{
> >                         this.p = page;
> >                         this.resultData = response;
> >                         this.totalRecords = response.totalRecs;
> > })
> > ```
> 
> @irrfan13 Once you fetch all the records from service, then only change the page number and then it will work correctly, I am also facing the same problem.
> 
> For Ex :
> 
> getPage(page){
> this.service.getData(data).subscribe((response)=>{
> 
> ```
>                     this.resultData = response;
>                     this.totalRecords = response.totalRecs;
>                     this.p = page;
> ```
> })

@kanishkamehta20 either way page number is coming from the event but i am sending the page number to the service object and then i am giving the page number value to the template, after fetching records from service.
