### ISSUE TITLE
Unable to get either ng2-pagination or ngx-pagination to render after clean build

### ISSUE THREAD

**Issue by scookstlmo** [michaelbromley/ngx-pagination#188] opened 2017-08-22 17:00 UTC
Hi, thanks for contributing!

This project is maintained in my spare time, so in order to help me address your issue as quickly as 
possible, please provide as much of the following information as you can.

-- Michael 

I was having issues with ngx-pagination using Angular 2.3.1 (page wouldn't render, just hang) so I went back to a simple tutorial at https://ciphertrick.com/2016/10/19/simple-pagination-for-angular2-applications/ using ng2-pagination and Angular 2.1.2 and that doesn't work either, the page just won't render, no errors just hangs up.  After removing the ngx-pagination code, page went back to working without issue.

=======

**Angular version**:

**ngx-pagination version**:

**Description of issue**:

**Steps to reproduce**:

**Expected result**:

**Actual result**:

**Demo**: (if possible, edit [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) and paste the link to your fork)

Any relevant code:
```

```

**Comment by michaelbromley** [comment] 2017-08-22 20:12
Hi,

I'm not sure what to make of this without some more information. 

> the page just won't render, no errors just hangs up

Could it be that you have an infinite loop somewhere in your code? That's usually the cause of a page hanging in my experience.

If you share the code you used when you attempted to use ngx-pagination, I might be able to help further.

**Comment by scookstlmo** [comment] 2017-08-22 21:03
Since that post, I've made a number of changes to streamline:

**html template snippet:**  
         <div class='panel-footer' *ngIf='webAccounts && webAccounts.length'>
            <div class="text-center">
                <h2 class="subheader"></h2>
                  <ul>
                    <li *ngFor="let webAccount of webAccounts | paginate: { itemsPerPage: 3, currentPage: p, totalItems: webAccounts.length }"> ... </li>
                  </ul>

                  <pagination-controls (pageChange)="p = $event"></pagination-controls>
            </div>
        </div>
**ts snippet:**
import { Component, OnInit }  from '@angular/core';
import { NgxPaginationModule } from 'ngx-pagination';
import { IWebAccount } from './webAccount';
import { WebAccountService } from './webAccount.service';
import { AppComponent }  from '../app.component';


@Component({
    templateUrl: 'app/webaccounts/webAccount-list.component.html',
    styleUrls: ['app/webaccounts/webAccount-list.component.css']
})
export class WebAccountListComponent implements OnInit {

**Comment by scookstlmo** [comment] 2017-08-22 21:05
If I debug via VS Code, I'm getting pagination-controls is not a known element

**Comment by scookstlmo** [comment] 2017-08-22 21:10
if I comment out the panel-footer that contains the <pagination-controls then the page renders the list page without issue.  Does the pagination-control have to be in a separate component or can I access it from the NgxPaginationModule?

**Comment by michaelbromley** [comment] 2017-08-23 06:09
If you look at the [source for NgxPaginationModule](https://github.com/michaelbromley/ngx-pagination/blob/20a2db2501b842826e28031f5d0e2c894401a2b9/src/ngx-pagination.module.ts) you can see that there are 3 declarations being exported - `PaginatePipe, PaginationControlsComponent, PaginationControlsDirective`

This means that if you import the NgxPaginationModule into your own NgModule, they will be available for use. If the pagination-controls is not recognised, this suggests that it is not being imported into the module in which you wish to use it.

**Comment by scookstlmo** [comment] 2017-08-23 16:29
I'm getting 404s in lite-server:
1] 17.08.23 11:17:37 304 GET /node_modules/@angular/forms/bundles/forms.umd.js
[1] 17.08.23 11:17:37 404 GET /ngx-pagination
[1] 17.08.23 11:17:37 304 GET /app/app.component.js
[1] 17.08.23 11:17:37 304 GET /app/pagination.component.js
[1] 17.08.23 11:17:37 304 GET /app/home/welcome.component.js
[1] 17.08.23 11:17:37 304 GET /node_modules/@angular/http/bundles/http.umd.js
[1] 17.08.23 11:17:37 304 GET /app/webAccounts/webAccount-List.component.js
[1] 17.08.23 11:17:37 304 GET /node_modules/@angular/router/bundles/router.umd.js
[1] 17.08.23 11:17:37 304 GET /app/webAccounts/webAccount.module.js
[1] 17.08.23 11:17:37 304 GET /node_modules/@angular/forms/bundles/forms.umd.js
[1] 17.08.23 11:17:37 404 GET /ngx-pagination
although ngx-pagination is installed and is found in the node_modules directory and is found in package.json so clearly ngx-pagination isn't being loaded.  Any ideas as to what's going on?

**Comment by michaelbromley** [comment] 2017-08-23 19:58
Ok. This looks like a setup / config issue which is not related to this library per se. I suggest you take it to StackOverflow or some other source of advice, because I can't help with it.

Good luck getting it solved. I'm going to close this issue now. If you find that it *is* in fact an issue directly related to this library, please comment with details and I'll take another look.

**Closed by michaelbromley** 2017-08-23 19:58 UTC

**Comment by agadhicham** [comment] 2019-02-18 16:44
try to add this ligne in the type script file app.mdule : import {NgxPaginationModule} from 'ngx-pagination'; // <-- import the module
then import int the variables table imports [NgxPaginationModule]
